CREATE TABLE [dbo].[VOTER_REGISTRATION] (
    [NID]         INT          NOT NULL PRIMARY KEY,
    [NAME]          VARCHAR (50) NULL,
    [PASSWORD]			VARCHAR (50) NULL,
    [ADDRESS]            VARCHAR (50) NULL,
	[PICTURE]            IMAGE        NULL,
);
SELECT* FROM VOTER_REGISTRATION
CREATE TABLE [dbo].[ADMIN] (
    [NAME]          VARCHAR (50) NULL,
    [PASSWORD]			VARCHAR (50) NULL,
);
SELECT* FROM ADMIN
INSERT INTO ADMIN VALUES ('RUDDRO','11111');
DROP TABLE ADMIN_CONTROL
CREATE TABLE [dbo].[ADMIN_CONTROL] 
(
    [CANDIDATE_NUMBER]      INT          NOT NULL PRIMARY KEY,
    [NAME]					VARCHAR (50) NOT NULL,
    [PICTURE]				IMAGE    NOT  NULL,
	[VOTE_COUNT]           INT      DEFAULT 0,
);
SELECT* FROM ADMIN_CONTROL
delete from ADMIN_CONTROL